### ISSUE TITLE
Mod Organizer 2 just don't launch!

### ISSUE THREAD

**Issue by marcelo-adriano** [Furglitch/modorganizer2-linux-installer#115]
Hi,
I installed MO2 just like describe in readme. But when I try launch MO2, nothing happens.

Log:
Running /home/julio/Games/mod-organizer-2/run.sh
Initial process has started with pid 37579
Game is considered started.
Searching for Steam in '/home/julio/.local/share/Steam'
Found Steam
Searching for game in library '/home/julio/.local/share/Steam'
Found game
Searching for 'Proton 5.*' in library '/home/julio/.local/share/Steam'
Found Proton

	PATH='/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin' \
	LD_LIBRARY_PATH='/home/julio/.local/share/Steam/steamapps/common/Proton 5.0/dist/lib64:/home/julio/.local/share/Steam/steamapps/common/Proton 5.0/dist/lib:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i368-linux-gnu:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/julio/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:/opt/amdgpu-pro/lib/i386-linux-gnu:/opt/amdgpu-pro/lib/x86_64-linux-gnu:/opt/cuda/lib64:/opt/cuda/nvvm/lib64:/opt/cuda/extras/CUPTI/lib64:/usr/lib/libfakeroot:/usr/lib32:/usr/lib/opencollada:/usr/lib/openmpi:/usr/lib' \
	STEAM_COMPAT_DATA_PATH='/home/julio/.local/share/Steam/steamapps/compatdata/489830' \
	SteamGameId=489830 \
	SteamAppId=489830 \
	WINEDLLOVERRIDES='xaudio2_7=n,b;' PULSE_LATENCY_MSEC=90 \
	\
	'/home/julio/.local/share/Steam/steamapps/common/Proton 5.0/proton' run '/home/julio/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe' 

esync: up and running.
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Setting breakpad minidump AppID = 489830
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198046286019 [API loaded no]
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
wine: Unhandled exception 0x20474343 in thread c8 at address 000000007B00FC3E (thread 00c8), starting debugger...
Unhandled exception: 0x20474343 in 64-bit code (0x000000007b00fc3e).
Register dump:
 rip:000000007b00fc3e rsp:000000000021dff0 rbp:000000000021e440 eflags:00000206 (   - --  I   - -P- )
 rax:000000000021e030 rbx:0000000007cf5140 rcx:000000000021e010 rdx:0000000000000000
 rsi:000000000021e108 rdi:000000000021e038  r8:0000000000000001  r9:000000000021e100 r10:0000000007cf5200
 r11:0000000007cf5200 r12:0000000007cf5100 r13:000000000021e220 r14:000000000021e250 r15:000000000021e180
Stack dump:
0x000000000021dff0:  000000000021e010 0000000000000000
0x000000000021e000:  0000000000000000 0000000000000000
0x000000000021e010:  0000000020474343 0000000000000000
0x000000000021e020:  000000007b00fc3e 0000000000000001
0x000000000021e030:  0000000007cf5100 0000000000000000
0x000000000021e040:  0000000000000000 0000000007cf5180
0x000000000021e050:  0000000007cf5200 000000006231f798
0x000000000021e060:  0000000000000000 0000000000000000
0x000000000021e070:  0000000000000000 0000000000000000
0x000000000021e080:  0000000000000000 0000000007cf5140
0x000000000021e090:  000000006246a360 0000000007d17410
0x000000000021e0a0:  000000000021e440 0000000007cf5180
Backtrace:
=>0 0x000000007b00fc3e EntryPoint+0x9bde() in kernelbase (0x000000000021e440)
0x000000007b00fc3e EntryPoint+0x9bde in kernelbase: nop	
Modules:
Module	Address					Debug info	Name (165 modules)
PE	          220000-         59be000	Deferred        qt5webenginecore
PE	         59c0000-         5d6e000	Deferred        qt5quick
PE	         5d70000-         615f000	Deferred        qt5qml
PE	         6160000-         62ad000	Deferred        qt5network
PE	         62b0000-         6877000	Deferred        qt5core
PE	         6880000-         6911000	Deferred        msvcp140
PE	         6920000-         6939000	Deferred        vcruntime140
PE	         6940000-         6944000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	         6950000-         695c000	Deferred        vcruntime140_1
PE	         6960000-         6f96000	Deferred        qt5gui
PE	         6fa0000-         6fc1000	Deferred        qt5webchannel
PE	         6fd0000-         7022000	Deferred        qt5positioning
PE	         7040000-         7305000	Deferred        d3d11
PE	         7310000-         7362000	Deferred        qt5printsupport
PE	         7370000-         78c8000	Deferred        qt5widgets
PE	         78d0000-         78e6000	Deferred        qt5quickwidgets
PE	         78f0000-         791a000	Deferred        qt5websockets
PE	         7920000-         7a6a000	Deferred        uibase
PE	         7a70000-         7afe000	Deferred        qt5winextras
PE	         7b00000-         7cbb000	Deferred        usvfs_x64
PE	         7cc0000-         7cde000	Deferred        liblz4
PE	         8380000-         8384000	Deferred        api-ms-win-core-localization-l1-2-1
PE	         8390000-         84ff000	Deferred        qwindows
PE	         8500000-         8597000	Deferred        openvr_api_dxvk
PE	        61540000-        61544000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	        61f40000-        61f44000	Deferred        wtsapi32
PE	        620c0000-        620c4000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	        62140000-        62145000	Deferred        uxtheme
PE	        62240000-        624c8000	Deferred        d3d9
PE	        62600000-        62604000	Deferred        usp10
PE	        63140000-        63145000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	        637c0000-        6383f000	Deferred        winmm
PE	        638c0000-        638c5000	Deferred        dwmapi
PE	        64340000-        64347000	Deferred        winhttp
PE	        64940000-        64945000	Deferred        shcore
PE	        64b80000-        64b85000	Deferred        hid
PE	        64d40000-        64d47000	Deferred        vulkan-1
PE	        65000000-        6502c000	Deferred        ole32
PE	        65780000-        65785000	Deferred        version
PE	        66440000-        6644a000	Deferred        msacm32
PE	        67d00000-        67d04000	Deferred        userenv
PE	        68a40000-        68a4f000	Deferred        shlwapi
PE	        68ac0000-        68ac4000	Deferred        api-ms-win-crt-time-l1-1-0
PE	        69380000-        69385000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	        69b80000-        69b84000	Deferred        api-ms-win-crt-environment-l1-1-0
PE	        6a100000-        6a10d000	Deferred        oleaut32
PE	        6a4c0000-        6a4c4000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	        6a700000-        6a717000	Deferred        setupapi
PE	        6b2c0000-        6b2e2000	Deferred        wininet
PE	        6b6c0000-        6b76d000	Deferred        comdlg32
PE	        6b880000-        6b884000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	        6bec0000-        6bec6000	Deferred        imm32
PE	        6d580000-        6d585000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	        6d9c0000-        6d9cd000	Deferred        mpr
PE	        6dd80000-        6dd85000	Deferred        api-ms-win-crt-string-l1-1-0
PE	        6e280000-        6e285000	Deferred        ncrypt
PE	        6e340000-        6e344000	Deferred        api-ms-win-core-synch-l1-2-0
PE	        6e6c0000-        6e715000	Deferred        comctl32
PE	        6eb00000-        6eb06000	Deferred        wintab32
PE	        6fbc0000-        6fbcb000	Deferred        rpcrt4
PE	        70580000-        70586000	Deferred        api-ms-win-crt-math-l1-1-0
PE	        70a00000-        70a04000	Deferred        dhcpcsvc
PE	        71140000-        71154000	Deferred        urlmon
PE	        71240000-        71246000	Deferred        jsproxy
ELF	        7a800000-        7aa0a000	Deferred        opengl32<elf>
  \-PE	        7a850000-        7aa0a000	\               opengl32
PE	        7b000000-        7b013000	Export          kernelbase
ELF	        7b400000-        7b682000	Deferred        kernel32<elf>
  \-PE	        7b410000-        7b682000	\               kernel32
ELF	        7bc00000-        7bf19000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bf19000	\               ntdll
ELF	        7c000000-        7c003000	Deferred        <wine-loader>
PE	       140000000-       1405e8000	Deferred        modorganizer
PE	       180000000-       18003f000	Deferred        qt5webenginewidgets
PE	     7ff33a60000-     7ff33a78000	Deferred        dxva2
ELF	    7f1755e8b000-    7f17560e8000	Deferred        libvulkan.so.1
ELF	    7f17560e8000-    7f1756104000	Deferred        kerberos<elf>
  \-PE	    7f17560f0000-    7f1756104000	\               kerberos
ELF	    7f1756104000-    7f1756308000	Deferred        libkeyutils.so.1
ELF	    7f1756308000-    7f175654d000	Deferred        libdbus-1.so.3
ELF	    7f175654d000-    7f1756756000	Deferred        libkrb5support.so.0
ELF	    7f1756756000-    7f175695a000	Deferred        libcom_err.so.2
ELF	    7f175695a000-    7f1756b83000	Deferred        libk5crypto.so.3
ELF	    7f1756b83000-    7f1756e56000	Deferred        libkrb5.so.3
ELF	    7f1756e56000-    7f1757067000	Deferred        libavahi-client.so.3
ELF	    7f1757067000-    7f1757274000	Deferred        libavahi-common.so.3
ELF	    7f1757274000-    7f17574b3000	Deferred        libgssapi_krb5.so.2
ELF	    7f17574b3000-    7f1757707000	Deferred        libcups.so.2
ELF	    7f1757709000-    7f175790f000	Deferred        libxfixes.so.3
ELF	    7f175790f000-    7f1757b19000	Deferred        libxcursor.so.1
ELF	    7f1757b19000-    7f1757d29000	Deferred        libxi.so.6
ELF	    7f1757d29000-    7f1757f2c000	Deferred        libxcomposite.so.1
ELF	    7f1757f2c000-    7f1758136000	Deferred        libxrandr.so.2
ELF	    7f1758136000-    7f1758340000	Deferred        libxrender.so.1
ELF	    7f1758340000-    7f1758545000	Deferred        libxxf86vm.so.1
ELF	    7f1758545000-    7f1758748000	Deferred        libxinerama.so.1
ELF	    7f1758748000-    7f175894e000	Deferred        libxdmcp.so.6
ELF	    7f175894e000-    7f1758b52000	Deferred        libxau.so.6
ELF	    7f1758b52000-    7f1758d72000	Deferred        libxcb.so.1
ELF	    7f1758d72000-    7f17590ad000	Deferred        libx11.so.6
ELF	    7f17590ad000-    7f17592bf000	Deferred        libxext.so.6
ELF	    7f17592bf000-    7f175938b000	Deferred        winex11<elf>
  \-PE	    7f17592d0000-    7f175938b000	\               winex11
ELF	    7f175938b000-    7f1759593000	Deferred        libffi.so.6
ELF	    7f1759593000-    7f175980d000	Deferred        libgmp.so.10
ELF	    7f175980d000-    7f1759a41000	Deferred        libhogweed.so.4
ELF	    7f1759a41000-    7f1759c77000	Deferred        libnettle.so.6
ELF	    7f1759c77000-    7f1759e8a000	Deferred        libtasn1.so.6
ELF	    7f1759e8a000-    7f175a0be000	Deferred        libidn.so.11
ELF	    7f175a0be000-    7f175a321000	Deferred        libp11-kit.so.0
ELF	    7f175a321000-    7f175a65a000	Deferred        libgnutls.so.30
ELF	    7f175a710000-    7f175a93a000	Deferred        libexpat.so.1
ELF	    7f175a93a000-    7f175ab70000	Deferred        libfontconfig.so.1
ELF	    7f175aba1000-    7f175adb8000	Deferred        libz.so.1
ELF	    7f175adb8000-    7f175b056000	Deferred        libfreetype.so.6
ELF	    7f175b156000-    7f175b1ad000	Deferred        winevulkan<elf>
  \-PE	    7f175b160000-    7f175b1ad000	\               winevulkan
ELF	    7f175b1ad000-    7f175b351000	Deferred        wined3d<elf>
  \-PE	    7f175b1d0000-    7f175b351000	\               wined3d
ELF	    7f175b351000-    7f175b398000	Deferred        dxgi<elf>
  \-PE	    7f175b360000-    7f175b398000	\               dxgi
ELF	    7f175b398000-    7f175b43f000	Deferred        dwrite<elf>
  \-PE	    7f175b3a0000-    7f175b43f000	\               dwrite
ELF	    7f175b43f000-    7f175b490000	Deferred        secur32<elf>
  \-PE	    7f175b450000-    7f175b490000	\               secur32
ELF	    7f175b490000-    7f175b50d000	Deferred        dbghelp<elf>
  \-PE	    7f175b4a0000-    7f175b50d000	\               dbghelp
ELF	    7f175b50d000-    7f175b56b000	Deferred        winspool<elf>
  \-PE	    7f175b520000-    7f175b56b000	\               winspool
ELF	    7f175b56b000-    7f175b592000	Deferred        bcrypt<elf>
  \-PE	    7f175b570000-    7f175b592000	\               bcrypt
ELF	    7f175b592000-    7f175b69a000	Deferred        crypt32<elf>
  \-PE	    7f175b5a0000-    7f175b69a000	\               crypt32
ELF	    7f175b69a000-    7f175b6b4000	Deferred        libresolv.so.2
ELF	    7f175b6b4000-    7f175b6dc000	Deferred        dnsapi<elf>
  \-PE	    7f175b6c0000-    7f175b6dc000	\               dnsapi
ELF	    7f175b6dc000-    7f175b817000	Deferred        ucrtbase<elf>
  \-PE	    7f175b710000-    7f175b817000	\               ucrtbase
ELF	    7f175b817000-    7f175b859000	Deferred        ws2_32<elf>
  \-PE	    7f175b820000-    7f175b859000	\               ws2_32
ELF	    7f175b859000-    7f175b88c000	Deferred        iphlpapi<elf>
  \-PE	    7f175b860000-    7f175b88c000	\               iphlpapi
ELF	    7f175b88c000-    7f175b8d6000	Deferred        netapi32<elf>
  \-PE	    7f175b890000-    7f175b8d6000	\               netapi32
ELF	    7f175b8d6000-    7f175c322000	Deferred        shell32<elf>
  \-PE	    7f175b8f0000-    7f175c322000	\               shell32
ELF	    7f175c322000-    7f175c40e000	Deferred        msvcrt<elf>
  \-PE	    7f175c340000-    7f175c40e000	\               msvcrt
ELF	    7f175c40e000-    7f175c452000	Deferred        sechost<elf>
  \-PE	    7f175c420000-    7f175c452000	\               sechost
ELF	    7f175c452000-    7f175c4cc000	Deferred        advapi32<elf>
  \-PE	    7f175c460000-    7f175c4cc000	\               advapi32
ELF	    7f175c4cc000-    7f175c67c000	Deferred        gdi32<elf>
  \-PE	    7f175c4e0000-    7f175c67c000	\               gdi32
ELF	    7f175c77c000-    7f175ca02000	Deferred        user32<elf>
  \-PE	    7f175c7a0000-    7f175ca02000	\               user32
ELF	    7f175ce35000-    7f175ce49000	Deferred        libnss_files.so.2
ELF	    7f175d049000-    7f175d260000	Deferred        libgcc_s.so.1
ELF	    7f175d260000-    7f175d3a5000	Deferred        libm.so.6
ELF	    7f175d3a5000-    7f175d3b0000	Deferred        librt.so.1
ELF	    7f175d3b3000-    7f175d3b9000	Deferred        libdl.so.2
ELF	    7f175d3bb000-    7f175d582000	Deferred        libc.so.6
ELF	    7f175d582000-    7f175d5a4000	Deferred        libpthread.so.0
ELF	    7f175d5a4000-    7f175d946000	Export          libwine.so.1
ELF	    7f175d948000-    7f175d976000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000020 steam.exe
	0000009c    0
	00000024    0
00000038 services.exe
	00000098    0
	00000080    0
	0000006c    0
	00000054    0
	00000050    0
	0000004c    0
	00000040    0
	0000003c    0
00000044 winedevice.exe
	00000060    0
	0000005c    0
	00000058    0
	00000048    0
00000064 plugplay.exe
	00000074    0
	00000070    0
	00000068    0
00000078 winedevice.exe
	00000094    0
	00000090    0
	0000008c    0
	00000088    0
	00000084    0
	0000007c    0
000000a0 explorer.exe
	000000b8    0
	000000b4    0
	000000a8    0
	000000a4    0
000000c4 (D) Z:\home\julio\Games\mod-organizer-2\ModOrganizer2\ModOrganizer.exe
	000000c8    0 <==
System information:
    Wine build: wine-5.0-655-g2409bd1
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.7.7-arch1-1
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 0

**Comment by LithianFI** [comment]
Make sure your wine prefix has either .net 4.8 or preferably mono 5.1.0 installed as well as VC runtime 2019.

**Comment by rockerbacon** [comment]
See #111
