### ISSUE TITLE
Mod Organizer 2 Crash on Opening Settings

### ISSUE THREAD

**Issue by ominitay** [Furglitch/modorganizer2-linux-installer#151]
At this point, MO2 is unusable, since settings can't be accessed. I have uploaded logs here, and commented at the point at which I attempt to open settings (line 2195). I am using the latest **stable** release (my previous issue was caused by using the latest release). The prefix is brand new (I deleted it and ran FO4 again before installing). 
My OS is Arch, with the kernel `5.8.5-arch1-1`. 
I am using the latest version of winetricks from the master branch.
I installed MO2 to mod fallout 4.
[steam-377160.log](https://github.com/rockerbacon/lutris-skyrimse-installers/files/5219847/steam-377160.log)

**Comment by rockerbacon** [comment]
See if [this](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/111#issuecomment-662503841) helps

**Comment by Ominitay** [comment]
Hmm. I've just tried installing it again (so a week later), with no change to my installation process or configuration, but the settings menu works now. :thinking: Nothing at all has changed about my configuration either, apart from the fact that I completely reset my FO4 install for CTD issues. If there is anything I can do to try and work out why this happened, just tell me to and I'll do it.

**Comment by Ominitay** [comment]
As a note, I did not need to follow those instructions, but I had already done so before, to no avail.
