### ISSUE TITLE
MO2 all plugins fail to load

### ISSUE THREAD

**Issue by XMais** [Furglitch/modorganizer2-linux-installer#159]
Running it with your recommended settings (Install via Steam, Proton 5.0-9, runonce, install MO2 via your script) always ends up crashing all of MO2's plugins.

The message I get is:
```
Unhandled Exception:
System.InvalidProgramException: Invalid IL code in <Module>:InstallerFomodCSharp.settings (InstallerFomodCSharp modopt(System.Runtime.CompilerServices.IsConst)* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst),QList<MOBase::PluginSetting>*): IL_0053
```
On the next start, MO2 tells me the plugin "installer_fomod_csharp.dll" has caused a crash and asks whether I want to disable it. If I choose yes, the next plugin will crash (for example installer_bain.dll). This continues until MO2 launches but without any plugin to handle or install mods - i.e. I can't even install a simple zip-mod.

ubuntu 20.4.1 LTS
NV GTX 1060 6GB
Ryzen 5 3600
Proton 5.0-9

**Comment by rockerbacon** [comment]
Can you check if [release 2.8.5](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.8.5) fixes this?

**Comment by XMais** [comment]
Yes, it does. The MO2 log is full of errors about those plugins but it seems ignorable, all installers work so far

[2020-10-24 20:08:56.316 E] GetFileVersionInfoSizeW() failed on 'Z:\opt\lutris\games\mod-organizer-2\ModOrganizer2\plugins\installer_fomod.dll', Resource data not found. (0x714)

Thanks, dude :)
