### ISSUE TITLE
Installation Error Could not find 'Skyrim Special Edition' in your Steam library

### ISSUE THREAD

**Issue by Natey214** [Furglitch/modorganizer2-linux-installer#160]
I have run Skyrim Special Edition from my Steam Library and have the proton version set to 5.0.9 but have also tried 5.13-1. I used the 2.8.4 installer.

**Comment by rockerbacon** [comment]
Did you by any chance move the game between different Steam libraries at some point? Sometimes Steam doesn't properly clean game files and the script is unable to determine where the game actually is.

If you did, you can remove the files in the old library:

1. Identify the location of the library where the game was previously installed
2. Delete the directory `<old library location>/compatdata/489830`
3. Delete the directory `<old library location>/common/Skyrim Special Edition`

**Comment by Natey214** [comment]
This worked, thank you for your help and for an amazing project!

**Comment by rulatir** [comment]
How does one go about identifying previous/obsolete/semi-erased/half-no-longer-there/your-archeologist-might-know-but-you-won't library locations? How does one go about making 101% sure that a location I found is really obsolete and "dangling", and deleting it won't cause a disaster? You say `<old library location>` as if this were a piece of information everyone has printed and pinned to the cork table. In reality, determining this location is a Big Unsolved Subproblem of your solution.

**Comment by SelphisThaFish** [comment]
> @rockerbacon, how does one go about identifying previous/obsolete/semi-erased/half-no-longer-there/your-archeologist-might-know-but-you-won't library locations? How does one go about making 101% sure that a location I found is really obsolete and "dangling", and deleting it won't cause a disaster? You say `<old library location>` as if this were a piece of information everyone has printed and pinned to the cork table. In reality, determining this information is a Big Unsolved Subproblem of your solution.

Just use your file manager to search for common and find the one that's not your current install location. Mine was under .share because of an earlier flatpak steam installation. Steam only has one install path for core libraries as far as I know.
