### ISSUE TITLE
Implement file decompression utility

### ISSUE THREAD

**Issue by rockerbacon** [Furglitch/modorganizer2-linux-installer#186]
One of the features currently provided by Lutris is file decompression. Nothing too complex is required, a simple utility that can handle the following formats should suffice:

- tar.gz
- zip
- 7z

**Comment by jthistle** [comment]
What branch are you working on for this stuff? I've got some time on my hands so would be happy to help out :)

(especially since I'm dying to play some modded Skyrim again lol)
