### ISSUE TITLE
Linking MO2 with the version of LOOT provided in the AUR cannot properly launch with each other - Error 87 ERROR_INVALID_PARAMETER: Invalid parameter. (0x57)

### ISSUE THREAD

**Issue by SpectreSpecter** [Furglitch/modorganizer2-linux-installer#236]
### The Problem:

When linking to /opt/loot/LOOT and launching it through MO2, I get this error;

**CANNOT START LOOT**

_This error typically happens because an antivirus has deleted critical files from Mod Organizer's installation folder or has made them generally inaccessible. Add an exclusion for Mod Organizer's installation folder in your antivirus, reinstall Mod Organizer and try again._

```
Error 87 ERROR_INVALID_PARAMETER: Invalid parameter. (0x57)
 . binary: 'Z:\opt\loot\LOOT'
 . owner: GetEffectiveRightsFromAclW(), Invalid function. (0x1)
 . rights: GetEffectiveRightsFromAclW(), Invalid function. (0x1)
 . arguments: ''
 . cwd: '\opt\loot'
 . stdout: no, stderr: no, hooked: yes
 . MO elevated: yes
 . usvfs x86:ok x64:ok proxy_x86:ok proxy_x64:ok
```

Wrye Bash, FNIS, SSEEdit standalone versions all work and function perfectly in MO2 all properly linked up. This only has happened with LOOT. I am new with Linux, so I thought because the "GetEffectiveRightsFromAclW()" meant to chown LOOT to myself, but that ended in failure.

### To Reproduce:

To execute it, launch MO2 from Lutris, select LOOT from the executable, and click run

### Environment:

[Release version 2.8.6 of the Lutris Skyrim SE launcher provided by Rockerbacon](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.8.6) Which given the choice, I choosed steam play rather than purely wine
[Version 0.16.1-4 of LOOT provided in the AUR](https://aur.archlinux.org/packages/loot)
Linux Version: Manjaro kernel version 5.10.53-1

### Extra Details:

Went into the github of the actual Mod Organizer 2, found https://github.com/ModOrganizer2/modorganizer/issues/1383
I'll list the Extra details I went through to fix this as well.

- LOOT launches on its own without issue.
- I assume Visual C++ was included with building this version of MO2, and if not, I don't know the WINEPREFIX command to get it in.
- LOOT is still in it's opt folder in opt/loot/LOOT, so I am not sure if I should move that or not.
- I have reinstalled MO2 after installing LOOT
- If there is another firewall/antivirus that came preinstalled with Manjaro, I am unaware of it and gufw is the only firewall I know I have installed and it has been disabled for testing this problem.
- I have not ran this with elevated privileges, and I know sudo su would be involved, but I am not going to do that.

I have not yet figured out to fix this and I plan to delete Lutris in it's entirety to then reinstall it, reinstall MO2, and link it with the LOOT I have installed. Will inform you if that worked or not. EDIT: I have done so and I still have the exact same error.

**Comment by trevorgunn** [comment]
Just as you need to do special things to get windows programs to run on linux, you also need to do special things to get linux programs to run from within wine. You can maybe get it to work (1) but it's going to be far easier to use the windows version of loot instead.

1: https://stackoverflow.com/questions/6004070/execute-shell-commands-from-program-running-in-wine
