### ISSUE TITLE
Proton 5 skyrim issues

### ISSUE THREAD

**Issue by TerminallyDied** [Furglitch/modorganizer2-linux-installer#243]
with the proton 5 version that you need to have to actually run skyrim with mods i get _really_ bad performance its way worse then normal, and with that proton version textures glitch allot, flickering on diffrent spots of npc's. 
is there a way to avoid using proton 5, or is there a fix for it? 
i would really like to play skyrim with mods without having these issues.

texture glitching:
![image](https://user-images.githubusercontent.com/41258148/136656689-4a7e7866-ddc0-4cbb-abcf-7d1e9150cd35.png)

**Comment by rockerbacon** [comment]
As far as official Steam Proton goes, there is no way to use Mod Organizer 2 without Proton 5. That is the only version where USVFS isn't broken and without USVFS, Mod Organizer 2 isn't able to load any mods.

The alternatives are experimenting with unofficial versions, such as Proton-GE, or using a different mod manager, such as Vortex.

**Comment by LithRakoon** [comment]
i made a fork of a really nice fork fixing allot of issues
https://github.com/LithRakoon/lutris-skyrimse-installers

**Comment by rockerbacon** [comment]
> i made a fork of a really nice fork fixing allot of issues https://github.com/LithRakoon/lutris-skyrimse-installers

Thanks, I'll take a look at the changes and bring them to the mainline as soon as version 3 goes stable. Which Proton versions have you found to work with CrezyDud's fix?

**Comment by rockerbacon** [comment]
Pre-release [4.0.0](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/4.0.0) is out and should allow using newer versions of Proton and custom Proton versions as well.

**Comment by LithRakoon** [comment]
awesome
