### ISSUE TITLE
Wrong SKSE version Skyrim SE

### ISSUE THREAD

**Issue by TerminallyDied** [Furglitch/modorganizer2-linux-installer#266]
in your recent commit you updated SKSE for skyrim SE to 2.1.4, but this version is ONLY for skyrim Anniversary edition.
you need to regress the Skyrim SE version back to 2.0.20 and make a seperate install option for skyrim Anniversary edition.

**Comment by rockerbacon** [comment]
2.1.4 seems to be the correct version for the latest SE version. From the SKSE download page:

> If you are using the latest version on Steam, download the AE build. The older build supporting 1.5.97 is still around to support people who have downgraded their installation or otherwise prevented updates.

**Comment by LithRakoon** [comment]
you can see on https://skse.silverlock.org/ that it says SE build and AE build
![image](https://user-images.githubusercontent.com/41258148/148253600-bdc2a0d2-79d4-4e88-818f-1dddf3ac9133.png)

**Comment by rockerbacon** [comment]
Skyrim SE was also updated, `1.6.342` is the latest Skyrim SE version. You'll be in `1.5.97` if you have prevented Steam from updating the game.

I tested and SKSE64 2.0.20 will warn about the game version when trying to use it on a newly installed Skyrim SE.
