### ISSUE TITLE
Non-existent Skyrim SE install found

### ISSUE THREAD

**Issue by Hello-User** [Furglitch/modorganizer2-linux-installer#342]
I'm running the install script on a steamdeck with the game installed on an SD Card.

```
INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/deck/.local/share/Steam'
INFO: steam not found in '/home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/deck/.local/share/Steam'
```

However, Skyrim isn't in the library folder located at the found path. There isn't even an appmanifest to indicate steam thinks Skyrim is there. The script fails because it can't find ```SkyrimLauncher.exe```.

Specifying the library path manually by exporting STEAM_LIBRARY
```
export STEAM_LIBRARY="/run/media/mmcblk0p1/SteamLibrary/"
```

results in Skyrim not being found at all. Any help is appreciated.

**Comment by jake770321** [comment]
Had a similar issue where the script doesn't always work if the game is installed on a secondary drive. Try creating a symlink and see if that works.

**Comment by Heasterian** [comment]
Same issue, probably due to instaling game on SD Card.

**Comment by Heasterian** [comment]
Temporarly on Deck mounting sdcard install directory to default one works, but for some reason It's starting skse instead of MO2. Renaming skse_loader.exe fixed it for me.

**Comment by rockerbacon** [comment]
Will be handled in #496
