### ISSUE TITLE
FNV Wine: Nexus Downloads Broken

### ISSUE THREAD

**Issue by ajventer** [Furglitch/modorganizer2-linux-installer#50]
Attempting to download with manager for New Vegas pops up the NXM registration dialog, activating it to point at New Vegas modorganizer doesn't help, it will continue to only pop up the registration dialog forever.
This makes it impossible to use the download with manager for New Vegas.

The problem appears to be specific to New Vegas, and may be related to Nexus changing the game name of New Vegas from "FalloutNV" to "NewVegas" in recent months.

**Comment by rockerbacon** [comment]
There was a fix in #46, deployed in [2.6.3](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.6.3). Make sure you're not using an older version for Fallout New Vegas.

**Comment by rockerbacon** [comment]
This prompt appears when `nxmhandler.exe` is started without passing a nxm link. Could you show me the contents of `download.sh` inside your MO2 installation?

**Comment by ajventer** [comment]
That put me in the right direction - it was missing the $1 at the end, not sure how it got lost, but I put it back and the downloads are working now.

**Comment by rockerbacon** [comment]
Checked the code and the script is missing the $1. Reopening until a fix is released
