### ISSUE TITLE
Error when Proton is installed in secondary library

### ISSUE THREAD

**Issue by Oscar-Macdonald** [Furglitch/modorganizer2-linux-installer#54]
After installing for Skyrim SE I get the following error:
`Could not find Proton version matching 'Proton 5.*' in directory '$HOME/.steam/steam/steamapps/common/'`
I checked in Steam where Proton is installed. My install is in a secondary library. (go to Library, ensure Tools is selected, right click Proton 5.0 -> Properties..., select the Local Files tab and select Browse Local Files to get the install location.)
What would be the possible solutions to this, besides moving the install folder? Would it be possible to create a symbolic link?

**Comment by rockerbacon** [comment]
Add the argument `--proton-libdir 'path/to/secondary/library'` in Lutris: right click MO2 in Lutris > Configure > Game Options.

**Comment by rockerbacon** [comment]
Feel free to close the issue if that solves your problem
