### ISSUE TITLE
Protontricks flatpak error on steam deck even with protontricks installed from discover

### ISSUE THREAD

**Issue by JackYansongLi** [Furglitch/modorganizer2-linux-installer#542]
I followed the installation guide to install protontricks through discover app on my steam deck. However, when I run ./install.sh, it still says that 
```shell 
Error: Using non-flatpak Protontricks on SteamOS
```
Then, I manually deleted the following lines in check_dependencies.sh

```shell
if [ "$os_id" == "steamos" ] && [ "$("$utils/protontricks.sh" get-release)" != "flatpak" ]; then
	log_error "Using non-flatpak Protontricks on SteamOS"
	"$dialog" errorbox \
		"Only Flatpak releases of Protontricks are supported on SteamOS.\nPlease install Protontricks through the Discover app and try again."
	exit 1
fi
```

This time when I run ./install.sh, I get
```console
INFO: steam not found in '/home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
```

**Comment by BJT207** [comment]
Running `pipx uninstall protontricks` seemed to fix the issue for me

**Comment by rockerbacon** [comment]
> Running `pipx uninstall protontricks` seemed to fix the issue for me

This indicates multiple different Protontricks installs which the installer does not account for. Should be fixable by editing the script to prefer Flatpak whenever available.
