### ISSUE TITLE
ERROR_INTERNAL_ERROR when trying to launch SKSE

### ISSUE THREAD

**Issue by neosheo** [Furglitch/modorganizer2-linux-installer#575]
I installed and have gotten into MO2, I was able to download a mod manually (vortex downloads don't seem to be working when clicked in NexusMods). But when i click run with SKSE selected I get this error:

```
Error 1359 ERROR_INTERNAL_ERROR: Internalerror. (0x54f)

 . binary: 'E:\SteamLibrary\steamapps\common\Skyrim Special Edition\skse64_loader.exe'
 . owner: GetEffectiveRightsFromAclW(), Invalidfunction. (0x1)
 . rights: GetEffectiveRightsFromAclW(), Invalidfunction. (0x1)
 . arguments: ''
 . cwd: 'E:\SteamLibrary\steamapps\common\Skyrim Special Edition'
 . stdout: no, stderr: no, hooked: yes
 . MO elevated: yes
 . usvfs x86:ok x64:ok proxy_x86:ok proxy_x64:ok

```

I am on NixOS and am running MO2 off an external drive if that makes a difference.

**Comment by rockerbacon** [comment]
It’s a problem with SKSE or Wine being unable to execute something. Is it happening on a clean Proton 8 prefix without any mods installed? Is everything installed on the same drive?

**Comment by neosheo** [comment]
This is a clean proton 8 prefix. I only installed SkyUI before trying it. Everything (Game/Mods/MO2) are all on the same drive), it is btrfs drive if that makes a difference. Where does SKSE get installed?

**Comment by neosheo** [comment]
Ok, i got it working. I just uninstalled SkyUI. Updated SKSE to latest version. Then ran SKSE, it launched. Then I reinstalled SkyUI and it launched with SKSE

**Comment by neosheo** [comment]
@rockerbacon will this working with mods that say they need Microsoft Visual C++ Redistributable for Visual Studio 2019?

**Comment by rockerbacon** [comment]
Fixed by #573

**Comment by rockerbacon** [comment]
> @rockerbacon will this work with mods that say they need Microsoft Visual C++ Redistributable for Visual Studio 2019?

Should work

**Comment by rachelambda** [comment]
I have started getting this same error for FNV, no matter if I start NVSE, the game, or the launcher.

**Comment by rachelambda** [comment]
The full error I get is
```
Error 1359 ERROR_INTERNAL_ERROR: Internalerror. (0x54f)
 . binary: 'Z:\home\rachel\.local\share\Steam\steamapps\common\Fallout New Vegas\nvse_loader.exe'
 . owner: GetEffectiveRightsFromAclW(), Invalidfunction. (0x1)
 . rights: GetEffectiveRightsFromAclW(), Invalidfunction. (0x1)
 . arguments: ''
 . cwd: 'Z:\home\rachel\.local\share\Steam\steamapps\common\Fallout New Vegas'
 . stdout: no, stderr: no, hooked: yes
 . MO elevated: yes
 . usvfs x86:ok x64:ok proxy_x86:ok proxy_x64:ok
```

**Comment by rachelambda** [comment]
nevermind, it turns out I was running the launcher outside of steam as it had just handled a nexusmods link, relaunching through steam works
