### ISSUE TITLE
EnableNonClientDpiScaling() failed for HWND 0xXXXXXX (120) (Call not implemented.)

### ISSUE THREAD

**Issue by Allexio** [Furglitch/modorganizer2-linux-installer#625]
Hi there, my logs are getting spammed with this error message.
![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/59694328/189d042e-5e26-43eb-98d7-893f2c8147b4)
Is there anything I can do to fix this?
Thanks!
I am on Fedora 40.

**Comment by swjzielinski** [comment]
It's an error from Wine. Wine doesn't have EnableNonClientDpiScaling implemented (it's a Windows function).
It doesn't matter, MO2 will work normally. There was a workaround mentioned in #467, but it was reported as not working in #409.

**Comment by Allexio** [comment]
> It's an error from Wine. Wine doesn't have EnableNonClientDpiScaling implemented (it's a Windows function). It doesn't matter, MO2 will work normally. There was a workaround mentioned in #467, but it was reported as not working in #409.

Okay so is there a way to disable this error report?
It seems to me that this is a bug that needs to be fixed.

**Comment by swjzielinski** [comment]
There's no way to stop this error from logging. It's popping up because of Wine, not because of MO2.

**Comment by swjzielinski** [comment]
Looks like it happens every time I mouse over something that produces a tooltip.
