### ISSUE TITLE
Skyrim SE: How to change graphics settings?

### ISSUE THREAD

**Issue by onegen-dev** [Furglitch/modorganizer2-linux-installer#718]
Just installed Skyrim SE for nostalgia and MO2 to manage mods, as it worked in the past. Started the game, and the graphics settings are a bit too high for my older computer and the game is not full-screen.

MO2 overrides the original launcher, so how can I select the lower preset now? I only found the INI Editor in MO, but that is far far too advanced for me. Sorry if I missed something obvious, but the "Skyrim Special Edition Launcher" just goes to MO ("instance already running").

EDIT: I tried to set "Arguments" to `NO_REDIRECT` and `NO_REDIRECT=1` but neither did anything.

**Comment by Liswolynski** [comment]
You can use BethINI, a user-friendly editor with a graphical user interface and helpful hints. Download it from the Nexus Mods page, launch it via Protontricks under Skyrim's prefix, and you're all set.

**Comment by Liswolynski** [comment]
Yes, you're right, the file should be located in "C:\users\steamuser\Documents\My Games\Skyrim Special Edition". If the file is missing, then you have to generate it by playing the game some time. Also, you can easily access this folder via MO2 shortcut: look at folder icon, then pick "Open INIs folder" from a drop down menu.

**Comment by Liswolynski** [comment]
You're not supposed to link BethINI to MO2. Just run it via Protontricks, choose the Skyrim prefix, make all your adjustments, and once you're done, simply close it.
