### ISSUE TITLE
support for steam overlay

### ISSUE THREAD

**Issue by soredake** [Furglitch/modorganizer2-linux-installer#85]
Would be nice to have steam overlay when skse is launched from mo2.

**Comment by rockerbacon** [comment]
Not something easy to do and probably not worth the effort. This can be achieved by adding MO2 as a Steam shortcut or by changing the launch options in the game to launch MO2.

To set the launch options, right click Skyrim on Steam > Properties > set launch options, then set this as the launch option:

```
bash "$HOME/.config/modorganizer2/instances/skyrim/run.sh" && echo %command% >/dev/null
```

**Comment by soredake** [comment]
This method works, thanks, can you add this to readme?

**Comment by rockerbacon** [comment]
> This method works, thanks, can you add this to readme?

I've talked about this in [a previous issue](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/57#issuecomment-637176380).

Sadly, I do not have the time to maintain a proper guide with all tricks and workarounds, even though it is something I know would greatly improve the project.

**Comment by LoneWolfHT** [comment]
> bash "$HOME/.config/modorganizer2/instances/skyrim/run.sh" && echo %command% >/dev/null

Still works, just had to change `/skyrim/` to `/skyrimspecialedition/`

Thanks!

**Comment by rockerbacon** [comment]
Latest version launches MO2 directly through Steam so the overlay should work just fine.
