### ISSUE TITLE
I've probably done something wrong.

### ISSUE THREAD

**Issue by Mathalor** [Furglitch/modorganizer2-linux-installer#86]
I've tried to install this multiple times.  It gets stuck trying to extract nvse.  I wait five minutes and then I cancel the installation (without deleting game files) and then I get errors:

Path = /home/USER/.cache/lutris/installer/mod-organizer-2/nvse/nvse_5_1_beta4.7z
Type = 7z
Physical Size = 712979
Headers Size = 4131
Method = LZMA2:6m LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 12
Files: 231
Size:       4902927
Compressed: 712979
2020-06-19 13:24:08,159: Cancelling installation of Mod Organizer 2

(lutris:4859): Gtk-CRITICAL **: 13:24:54.893: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.908: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.910: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.912: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.916: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.918: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.920: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.923: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.934: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.936: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.942: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.945: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.947: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.950: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.953: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.960: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.962: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.965: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.967: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.970: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.972: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.975: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.978: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.980: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.984: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.986: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.989: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.992: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.994: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:54.997: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:55.000: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:55.003: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:55.005: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:55.010: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:55.016: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:55.025: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4859): Gtk-CRITICAL **: 13:24:55.029: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

I don't have much technical or programming skill, and don't know how to find out what is happening.  I am running ubuntu 20.04 on an intel laptop.

**Comment by rockerbacon** [comment]
Check #74.

The extract features are provided by Lutris and there's little that can be done in this project to fix this.
