### ISSUE TITLE
MO2 not handling nxm links

### ISSUE THREAD

**Issue by Jamesdawg1977** [Furglitch/modorganizer2-linux-installer#92]
I went into the settings, hit the "associate with download with manager links" button, then went to nexus and clicked download on skyui. Firefox prompted me to select an app to open, I chose both ModOrganizer.exe, but nothing happened. I went back and tried nxmhandler.exe, and again, I click the link and nothing pops up. Any help would be greatly appreciated!

**Comment by rockerbacon** [comment]
You need to manually add the API key you get [from Nexus](https://www.nexusmods.com/users/myaccount?tab=api%20access) to Mod Organizer 2, under Preferences > Nexus.

NXM links are handled through `xdg`:
The script `$HOME/.local/bin/modorganizer-nxm-broker.sh` is called by `$HOME/.local/share/applications/modorganizer2-nxm-handler.desktop` which is registered as the default handler with the command `$ xdg-mime default modorganizer2-nxm-handler.desktop x-scheme-handler/nxm`.

Check the following:
1. All aforementioned files exist in you system
2. `xdg` is correctly configured:
```bash
$ xdg-mime query default x-scheme-handler/nxm
```
3. `$HOME/.local/bin` is in you path: 
```bash
$ grep -o "$HOME/.local/bin" <<< "$PATH"
```

**Comment by Jamesdawg1977** [comment]
I did as you said and it worked once, but now I'm back to the same problem. I rechecked everything and re-entered the commands but its still not working any more.

**Comment by rockerbacon** [comment]
> 2. `xdg` is correctly configured:
> 
> ```shell
> $ xdg-mime query default x-scheme-handler/nxm
> ```
> 
> 3. `$HOME/.local/bin` is in you path:
> 
> ```shell
> $ grep -o "$HOME/.local/bin" <<< "$PATH"
> ```

What's the output of these commands?

**Comment by Jamesdawg1977** [comment]
xdg-mime query default x-scheme-handler/nxm:
which: no modorganizer2-nxm-broker.sh in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
modorganizer2-nxm-handler.desktop

grep -o "$HOME/.local/bin" <<< "$PATH"

Second command didn't return anything.

**Comment by rockerbacon** [comment]
You're missing "$HOME/.local/bin" in your path. You need to add it to your `.bashrc`:

```bash
$ echo -e "\nexport PATH=\"$HOME/.local/bin:\$PATH\"" >> "$HOME/.bashrc"
```

Just out of curiosity: what distro are you using?

**Comment by Jamesdawg1977** [comment]
I'm running Arch. And I ran the command and double checked the .bashrc and its there, but the links still won't work. The commands now return:
modorganizer2-nxm-handler.desktop
/home/james/.local/bin
When I click on the mod manager download link, Firefox prompts me to select something to run it with. I've been selecting modorganizer2-nxm-handler.desktop, could that have something to do with it? Also, do you have any idea what that error I ran into while installing the mod was, or was that a completely different problem?

**Comment by rockerbacon** [comment]
It's possible that you are having problems because of #94. See if updating to [2.7.5](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.7.5) fixes your issue.

**Comment by Jamesdawg1977** [comment]
That didn't work either. I redid the commands just to make sure, but still no change.

**Comment by kleshas** [comment]
I've never got this working either.  On 2.7.5.  Ran the registration command.
Those commands above return:
modorganizer2-nxm-handler.desktop
/home/kleshas/.local/bin

Firefox never asks me anything.  Tried with MO2 open via lutris, and not open.

**Comment by rockerbacon** [comment]
Try to download a mod on Nexus. On the final page you'll see a message "if you are having trouble, **click here** to download manually", copy that link and run this command:

```bash
$ xdg-open 'paste link inside the quotes'
```

**Comment by Jamesdawg1977** [comment]
So I ran that and it returned:
[1] 1021771
[2] 1021772
[2]+  Done                    expires=1593664365

/home/james/.local/bin/modorganizer2-nxm-broker.sh: line 24: /home/james/.config/modorganizer2/instances/download.sh: No such file or directory
/usr/bin/xdg-open: line 881: x-www-browser: command not found

For the first half, I found download.sh in /home/james/.config/modorganizer2/instances/skyrim/download.sh. Should I update the broker.sh? And if so where? And the script doesn't extend for 881 lines, so I don't know what the other bit is about.

**Comment by kleshas** [comment]
Same error here.
That download.sh is in the path specified with the skyrim type i.e.
/home/kleshas/.config/modorganizer2/instances/skyrimspecialedition
where skyrimspecialedition is linked to /mnt/veracrypt3/Lutris/wabbajack/.  Interestingly, I have 3 instances - MO2, wabbajack, MO2SSE and only 2 linked folders in ~/.config/modorganizer2/instances.
MO2SSE was created before wabbajack, both are SSE.
MO2 is LE
